package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"

	"github.com/scale03/falena/internal/ebpf"
)

func main() {
	// Allow the current process to lock memory for eBPF maps.
	// By default, the RLIMIT_MEMLOCK is usually too low for BPF operations.
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatalf("failed to remove memlock rlimit: %v", err)
	}

	// Load pre-compiled eBPF objects (generated by bpf2go) into the kernel.
var objs ebpf.FalenaObjects

	// CORREZIONE 2: Assicurati che sia LoadFalenaObjects (F maiuscola)
	if err := ebpf.LoadFalenaObjects(&objs, nil); err != nil {
		log.Fatalf("failed to load ebpf objects: %v", err)
	}
	defer objs.Close() 

	// Attach the BPF program to the tracepoint.
	// We hook into sys_enter_openat to capture file opening attempts.
	tp, err := link.Tracepoint("syscalls", "sys_enter_openat", objs.SysEnterOpenat, nil)
	if err != nil {
		log.Fatalf("failed to link tracepoint: %v", err)
	}
	defer tp.Close()

	log.Println("=== Falena Agent Started ===")
	log.Println("Tracing openat() syscalls... Check /sys/kernel/debug/tracing/trace_pipe")
	
	// Block main goroutine and wait for termination signals (SIGINT/SIGTERM).
	// This ensures the BPF program remains loaded until explicit exit.
	stopper := make(chan os.Signal, 1)
	signal.Notify(stopper, os.Interrupt, syscall.SIGTERM)
	<-stopper

	log.Println("Received signal, detaching and exiting...")
}
